# Generated by Django 4.1.4 on 2023-05-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
