# Generated by Django 4.1.4 on 2023-05-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_saved_product_savedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='auth_token',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
