# Generated by Django 4.1.4 on 2023-05-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_account_auth_token_account_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='auth_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
