# Generated by Django 4.1.4 on 2023-06-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_account_address_remove_account_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='review',
            field=models.CharField(default='', max_length=500),
        ),
    ]
